Update setup.cfg metadata to work with setuptools v78.0.0.
The format with dashes was deprecated in setuptools v54.1.0 and causes the following error with setuptools v78.0.0:

    setuptools.errors.InvalidConfigError: Invalid dash-separated key 'description-file' in 'metadata' (setup.cfg), please use the underscore name 'description_file' instead.

See https://setuptools.pypa.io/en/stable/history.html#v78-0-0 for details.

Fixes #20.